language: objective-c
before_script:
  - export LANG=en_US.UTF-8
  - cd Demo ; pod install ; cd ..
xcode_workspace: Demo/RPBorderlessSegmentedControlDemo.xcworkspace
xcode_scheme: RPBorderlessSegmentedControlDemo