language: objective-c
before_install:
  - gem install cocoapods
before_script:
  - export LANG=en_US.UTF-8
  - cd Demo ; pod update ; cd ..
script: xctool -workspace Demo/RPBorderlessSegmentedControlDemo.xcworkspace -scheme RPBorderlessSegmentedControlDemo build